country_codes = {
    "AF": {"en": "Afghanistan", "it": "Afghanistan", "es": "Afganistán", "fr": "Afghanistan", "de": "Afghanistan"},
    "AX": {"en": "Aland Islands", "it": "Isole Aland", "es": "Islas Aland", "fr": "Îles Åland", "de": "Åland-Inseln"},
    "AL": {"en": "Albania", "it": "Albania", "es": "Albania", "fr": "Albanie", "de": "Albanien"},
    "DZ": {"en": "Algeria", "it": "Algeria", "es": "Argelia", "fr": "Algérie", "de": "Algerien"},
    "AS": {"en": "American Samoa", "it": "Samoa Americane", "es": "Samoa Americana", "fr": "Samoa Américaine", "de": "Amerikanisch-Samoa"},
    "AD": {"en": "Andorra", "it": "Andorra", "es": "Andorra", "fr": "Andorre", "de": "Andorra"},
    "AO": {"en": "Angola", "it": "Angola", "es": "Angola", "fr": "Angola", "de": "Angola"},
    "AI": {"en": "Anguilla", "it": "Anguilla", "es": "Anguila", "fr": "Anguilla", "de": "Anguilla"},
    "AQ": {"en": "Antarctica", "it": "Antartide", "es": "Antártida", "fr": "Antarctique", "de": "Antarktika"},
    "AG": {"en": "Antigua and Barbuda", "it": "Antigua e Barbuda", "es": "Antigua y Barbuda", "fr": "Antigua-et-Barbuda", "de": "Antigua und Barbuda"},
    "AR": {"en": "Argentina", "it": "Argentina", "es": "Argentina", "fr": "Argentine", "de": "Argentinien"},
    "AM": {"en": "Armenia", "it": "Armenia", "es": "Armenia", "fr": "Arménie", "de": "Armenien"},
    "AW": {"en": "Aruba", "it": "Aruba", "es": "Aruba", "fr": "Aruba", "de": "Aruba"},
    "AU": {"en": "Australia", "it": "Australia", "es": "Australia", "fr": "Australie", "de": "Australien"},
    "AT": {"en": "Austria", "it": "Austria", "es": "Austria", "fr": "Autriche", "de": "Österreich"},
    "AZ": {"en": "Azerbaijan", "it": "Azerbaigian", "es": "Azerbaiyán", "fr": "Azerbaïdjan", "de": "Aserbaidschan"},
    "BS": {"en": "Bahamas", "it": "Bahamas", "es": "Bahamas", "fr": "Bahamas", "de": "Bahamas"},
    "BH": {"en": "Bahrain", "it": "Bahrein", "es": "Baréin", "fr": "Bahreïn", "de": "Bahrain"},
    "BD": {"en": "Bangladesh", "it": "Bangladesh", "es": "Bangladesh", "fr": "Bangladesh", "de": "Bangladesch"},
    "BB": {"en": "Barbados", "it": "Barbados", "es": "Barbados", "fr": "Barbade", "de": "Barbados"},
    "BY": {"en": "Belarus", "it": "Bielorussia", "es": "Bielorrusia", "fr": "Biélorussie", "de": "Belarus"},
    "BE": {"en": "Belgium", "it": "Belgio", "es": "Bélgica", "fr": "Belgique", "de": "Belgien"},
    "BZ": {"en": "Belize", "it": "Belize", "es": "Belice", "fr": "Belize", "de": "Belize"},
    "BJ": {"en": "Benin", "it": "Benin", "es": "Benín", "fr": "Bénin", "de": "Benin"},
    "BM": {"en": "Bermuda", "it": "Bermuda", "es": "Bermudas", "fr": "Bermudes", "de": "Bermuda"},
    "BT": {"en": "Bhutan", "it": "Bhutan", "es": "Bután", "fr": "Bhoutan", "de": "Bhutan"},
    "BO": {"en": "Bolivia", "it": "Bolivia", "es": "Bolivia", "fr": "Bolivie", "de": "Bolivien"},
    "BA": {"en": "Bosnia and Herzegovina", "it": "Bosnia ed Erzegovina", "es": "Bosnia y Herzegovina", "fr": "Bosnie-Herzégovine", "de": "Bosnien und Herzegowina"},
    "BW": {"en": "Botswana", "it": "Botswana", "es": "Botsuana", "fr": "Botswana", "de": "Botswana"},
    "BV": {"en": "Bouvet Island", "it": "Isola Bouvet", "es": "Isla Bouvet", "fr": "Île Bouvet", "de": "Bouvetinsel"},
    "BR": {"en": "Brazil", "it": "Brasile", "es": "Brasil", "fr": "Brésil", "de": "Brasilien"},
    "IO": {"en": "British Indian Ocean Territory", "it": "Territorio britannico dell Oceano Indiano", "es": "Territorio Británico del Océano Índico", "fr": "Territoire Britannique de l'Océan Indien", "de": "Britisches Territorium im Indischen Ozean"},
    "BN": {"en": "Brunei", "it": "Brunei", "es": "Brunéi", "fr": "Brunei", "de": "Brunei"},
    "BG": {"en": "Bulgaria", "it": "Bulgaria", "es": "Bulgaria", "fr": "Bulgarie", "de": "Bulgarien"},
    "BF": {"en": "Burkina Faso", "it": "Burkina Faso", "es": "Burkina Faso", "fr": "Burkina Faso", "de": "Burkina Faso"},
    "BI": {"en": "Burundi", "it": "Burundi", "es": "Burundi", "fr": "Burundi", "de": "Burundi"},
    "KH": {"en": "Cambodia", "it": "Cambogia", "es": "Camboya", "fr": "Cambodge", "de": "Kambodscha"},
    "CM": {"en": "Cameroon", "it": "Camerun", "es": "Camerún", "fr": "Cameroun", "de": "Kamerun"},
    "CA": {"en": "Canada", "it": "Canada", "es": "Canadá", "fr": "Canada", "de": "Kanada"},
    "CV": {"en": "Cape Verde", "it": "Capo Verde", "es": "Cabo Verde", "fr": "Cap-Vert", "de": "Kap Verde"},
    "KY": {"en": "Cayman Islands", "it": "Isole Cayman", "es": "Islas Caimán", "fr": "Îles Caïmans", "de": "Kaimaninseln"},
    "CF": {"en": "Central African Republic", "it": "Repubblica Centrafricana", "es": "República Centroafricana", "fr": "République Centrafricaine", "de": "Zentralafrikanische Republik"},
    "TD": {"en": "Chad", "it": "Ciad", "es": "Chad", "fr": "Tchad", "de": "Tschad"},
    "CL": {"en": "Chile", "it": "Cile", "es": "Chile", "fr": "Chili", "de": "Chile"},
    "CN": {"en": "China", "it": "Cina", "es": "China", "fr": "Chine", "de": "China"},
    "CX": {"en": "Christmas Island", "it": "Isola di Natale", "es": "Isla de Navidad", "fr": "Île Christmas", "de": "Weihnachtsinsel"},
    "CC": {"en": "Cocos (Keeling) Islands", "it": "Isole Cocos (Keeling)", "es": "Islas Cocos (Keeling)", "fr": "Îles Cocos (Keeling)", "de": "Kokosinseln"},
    "CO": {"en": "Colombia", "it": "Colombia", "es": "Colombia", "fr": "Colombie", "de": "Kolumbien"},
    "KM": {"en": "Comoros", "it": "Comore", "es": "Comoras", "fr": "Comores", "de": "Komoren"},
    "CG": {"en": "Congo (Brazzaville)", "it": "Congo (Brazzaville)", "es": "Congo (Brazzaville)", "fr": "Congo (Brazzaville)", "de": "Kongo (Brazzaville)"},
    "CD": {"en": "Congo (Kinshasa)", "it": "Congo (Kinshasa)", "es": "Congo (Kinshasa)", "fr": "Congo (Kinshasa)", "de": "Kongo (Kinshasa)"},
    "CK": {"en": "Cook Islands", "it": "Isole Cook", "es": "Islas Cook", "fr": "Îles Cook", "de": "Cookinseln"},
    "CR": {"en": "Costa Rica", "it": "Costa Rica", "es": "Costa Rica", "fr": "Costa Rica", "de": "Costa Rica"},
    "CI": {"en": "Cote d'Ivoire", "it": "Costa d Avorio", "es": "Costa de Marfil", "fr": "Côte d'Ivoire", "de": "Elfenbeinküste"},
    "HR": {"en": "Croatia", "it": "Croazia", "es": "Croacia", "fr": "Croatie", "de": "Kroatien"},
    "CU": {"en": "Cuba", "it": "Cuba", "es": "Cuba", "fr": "Cuba", "de": "Kuba"},
    "CY": {"en": "Cyprus", "it": "Cipro", "es": "Chipre", "fr": "Chypre", "de": "Zypern"},
    "CZ": {"en": "Czech Republic", "it": "Cechia", "es": "República Checa", "fr": "République Tchèque", "de": "Tschechien"},
    "DK": {"en": "Denmark", "it": "Danimarca", "es": "Dinamarca", "fr": "Danemark", "de": "Dänemark"},
    "DJ": {"en": "Djibouti", "it": "Gibuti", "es": "Yibuti", "fr": "Djibouti", "de": "Dschibuti"},
    "DM": {"en": "Dominica", "it": "Dominica", "es": "Dominica", "fr": "Dominique", "de": "Dominica"},
    "DO": {"en": "Dominican Republic", "it": "Repubblica Dominicana", "es": "República Dominicana", "fr": "République Dominicaine", "de": "Dominikanische Republik"},
    "EC": {"en": "Ecuador", "it": "Ecuador", "es": "Ecuador", "fr": "Équateur", "de": "Ecuador"},
    "EG": {"en": "Egypt", "it": "Egitto", "es": "Egipto", "fr": "Égypte", "de": "Ägypten"},
    "SV": {"en": "El Salvador", "it": "El Salvador", "es": "El Salvador", "fr": "Salvador", "de": "El Salvador"},
    "GQ": {"en": "Equatorial Guinea", "it": "Guinea Equatoriale", "es": "Guinea Ecuatorial", "fr": "Guinée Équatoriale", "de": "Äquatorialguinea"},
    "ER": {"en": "Eritrea", "it": "Eritrea", "es": "Eritrea", "fr": "Érythrée", "de": "Eritrea"},
    "EE": {"en": "Estonia", "it": "Estonia", "es": "Estonia", "fr": "Estonie", "de": "Estland"},
    "ET": {"en": "Ethiopia", "it": "Etiopia", "es": "Etiopía", "fr": "Éthiopie", "de": "Äthiopien"},
    "FK": {"en": "Falkland Islands", "it": "Isole Falkland", "es": "Islas Malvinas", "fr": "Îles Malouines", "de": "Falklandinseln"},
    "FO": {"en": "Faroe Islands", "it": "Isole Faroer", "es": "Islas Feroe", "fr": "Îles Féroé", "de": "Färöer"},
    "FJ": {"en": "Fiji", "it": "Figi", "es": "Fiji", "fr": "Fidji", "de": "Fidschi"},
    "FI": {"en": "Finland", "it": "Finlandia", "es": "Finlandia", "fr": "Finlande", "de": "Finnland"},
    "FR": {"en": "France", "it": "Francia", "es": "Francia", "fr": "France", "de": "Frankreich"},
    "GF": {"en": "French Guiana", "it": "Guyana francese", "es": "Guayana Francesa", "fr": "Guyane Française", "de": "Französisch-Guayana"},
    "PF": {"en": "French Polynesia", "it": "Polinesia francese", "es": "Polinesia Francesa", "fr": "Polynésie Française", "de": "Französisch-Polynesien"},
    "TF": {"en": "French Southern Territories", "it": "Territori francesi del Sud", "es": "Territorios Australes Franceses", "fr": "Terres Australes Françaises", "de": "Französische Süd- und Antarktisgebiete"},
    "GA": {"en": "Gabon", "it": "Gabon", "es": "Gabón", "fr": "Gabon", "de": "Gabun"},
    "GM": {"en": "Gambia", "it": "Gambia", "es": "Gambia", "fr": "Gambie", "de": "Gambia"},
    "GE": {"en": "Georgia", "it": "Georgia", "es": "Georgia", "fr": "Géorgie", "de": "Georgien"},
    "DE": {"en": "Germany", "it": "Germania", "es": "Alemania", "fr": "Allemagne", "de": "Deutschland"},
    "GH": {"en": "Ghana", "it": "Ghana", "es": "Ghana", "fr": "Ghana", "de": "Ghana"},
    "GI": {"en": "Gibraltar", "it": "Gibilterra", "es": "Gibraltar", "fr": "Gibraltar", "de": "Gibraltar"},
    "GR": {"en": "Greece", "it": "Grecia", "es": "Grecia", "fr": "Grèce", "de": "Griechenland"},
    "GL": {"en": "Greenland", "it": "Groenlandia", "es": "Groenlandia", "fr": "Groenland", "de": "Grönland"},
    "GD": {"en": "Grenada", "it": "Grenada", "es": "Granada", "fr": "Grenade", "de": "Grenada"},
    "GP": {"en": "Guadeloupe", "it": "Guadalupa", "es": "Guadalupe", "fr": "Guadeloupe", "de": "Guadeloupe"},
    "GU": {"en": "Guam", "it": "Guam", "es": "Guam", "fr": "Guam", "de": "Guam"},
    "GT": {"en": "Guatemala", "it": "Guatemala", "es": "Guatemala", "fr": "Guatemala", "de": "Guatemala"},
    "GG": {"en": "Guernsey", "it": "Guernsey", "es": "Guernsey", "fr": "Guernesey", "de": "Guernsey"},
    "GN": {"en": "Guinea", "it": "Guinea", "es": "Guinea", "fr": "Guinée", "de": "Guinea"},
    "GW": {"en": "Guinea-Bissau", "it": "Guinea-Bissau", "es": "Guinea-Bisáu", "fr": "Guinée-Bissau", "de": "Guinea-Bissau"},
    "GY": {"en": "Guyana", "it": "Guyana", "es": "Guyana", "fr": "Guyane", "de": "Guyana"},
    "HT": {"en": "Haiti", "it": "Haiti", "es": "Haití", "fr": "Haïti", "de": "Haiti"},
    "HM": {"en": "Heard Island and McDonald Islands", "it": "Isole Heard e McDonald", "es": "Isla de Heard e Islas McDonald", "fr": "Îles Heard et MacDonald", "de": "Heard und McDonaldinseln"},
    "VA": {"en": "Holy See (Vatican City)", "it": "Santa Sede (Citta del Vaticano)", "es": "Santa Sede (Ciudad del Vaticano)", "fr": "Saint-Siège (Cité du Vatican)", "de": "Heiliger Stuhl (Vatikanstadt)"},
    "HN": {"en": "Honduras", "it": "Honduras", "es": "Honduras", "fr": "Honduras", "de": "Honduras"},
    "HK": {"en": "Hong Kong", "it": "Hong Kong", "es": "Hong Kong", "fr": "Hong Kong", "de": "Hongkong"},
    "HU": {"en": "Hungary", "it": "Ungheria", "es": "Hungría", "fr": "Hongrie", "de": "Ungarn"},
    "IS": {"en": "Iceland", "it": "Islanda", "es": "Islandia", "fr": "Islande", "de": "Island"},
    "IN": {"en": "India", "it": "India", "es": "India", "fr": "Inde", "de": "Indien"},
    "ID": {"en": "Indonesia", "it": "Indonesia", "es": "Indonesia", "fr": "Indonésie", "de": "Indonesien"},
    "IR": {"en": "Iran", "it": "Iran", "es": "Irán", "fr": "Iran", "de": "Iran"},
    "IQ": {"en": "Iraq", "it": "Iraq", "es": "Irak", "fr": "Irak", "de": "Irak"},
    "IE": {"en": "Ireland", "it": "Irlanda", "es": "Irlanda", "fr": "Irlande", "de": "Irland"},
    "IM": {"en": "Isle of Man", "it": "Isola di Man", "es": "Isla de Man", "fr": "Île de Man", "de": "Insel Man"},
    "IL": {"en": "Israel", "it": "Israele", "es": "Israel", "fr": "Israël", "de": "Israel"},
    "IT": {"en": "Italy", "it": "Italia", "es": "Italia", "fr": "Italie", "de": "Italien"},
    "JM": {"en": "Jamaica", "it": "Giamaica", "es": "Jamaica", "fr": "Jamaïque", "de": "Jamaika"},
    "JP": {"en": "Japan", "it": "Giappone", "es": "Japón", "fr": "Japon", "de": "Japan"},
    "JE": {"en": "Jersey", "it": "Jersey", "es": "Jersey", "fr": "Jersey", "de": "Jersey"},
    "JO": {"en": "Jordan", "it": "Giordania", "es": "Jordania", "fr": "Jordanie", "de": "Jordanien"},
    "KZ": {"en": "Kazakhstan", "it": "Kazakistan", "es": "Kazajistán", "fr": "Kazakhstan", "de": "Kasachstan"},
    "KE": {"en": "Kenya", "it": "Kenya", "es": "Kenia", "fr": "Kenya", "de": "Kenia"},
    "KI": {"en": "Kiribati", "it": "Kiribati", "es": "Kiribati", "fr": "Kiribati", "de": "Kiribati"},
    "KP": {"en": "North Korea", "it": "Corea del Nord", "es": "Corea del Norte", "fr": "Corée du Nord", "de": "Nordkorea"},
    "KR": {"en": "South Korea", "it": "Corea del Sud", "es": "Corea del Sur", "fr": "Corée du Sud", "de": "Südkorea"},
    "KW": {"en": "Kuwait", "it": "Kuwait", "es": "Kuwait", "fr": "Koweït", "de": "Kuwait"},
    "KG": {"en": "Kyrgyzstan", "it": "Kirghizistan", "es": "Kirguistán", "fr": "Kirghizistan", "de": "Kirgisistan"},
    "LA": {"en": "Laos", "it": "Laos", "es": "Laos", "fr": "Laos", "de": "Laos"},
    "LV": {"en": "Latvia", "it": "Lettonia", "es": "Letonia", "fr": "Lettonie", "de": "Lettland"},
    "LB": {"en": "Lebanon", "it": "Libano", "es": "Líbano", "fr": "Liban", "de": "Libanon"},
    "LS": {"en": "Lesotho", "it": "Lesotho", "es": "Lesoto", "fr": "Lesotho", "de": "Lesotho"},
    "LR": {"en": "Liberia", "it": "Liberia", "es": "Liberia", "fr": "Liberia", "de": "Liberia"},
    "LY": {"en": "Libya", "it": "Libia", "es": "Libia", "fr": "Libye", "de": "Libyen"},
    "LI": {"en": "Liechtenstein", "it": "Liechtenstein", "es": "Liechtenstein", "fr": "Liechtenstein", "de": "Liechtenstein"},
    "LT": {"en": "Lithuania", "it": "Lituania", "es": "Lituania", "fr": "Lituanie", "de": "Litauen"},
    "LU": {"en": "Luxembourg", "it": "Lussemburgo", "es": "Luxemburgo", "fr": "Luxembourg", "de": "Luxemburg"},
    "MO": {"en": "Macao", "it": "Macao", "es": "Macao", "fr": "Macao", "de": "Macau"},
    "MK": {"en": "North Macedonia", "it": "Macedonia del Nord", "es": "Macedonia del Norte", "fr": "Macédoine du Nord", "de": "Nordmazedonien"},
    "MG": {"en": "Madagascar", "it": "Madagascar", "es": "Madagascar", "fr": "Madagascar", "de": "Madagaskar"},
    "MW": {"en": "Malawi", "it": "Malawi", "es": "Malaui", "fr": "Malawi", "de": "Malawi"},
    "MY": {"en": "Malaysia", "it": "Malaysia", "es": "Malasia", "fr": "Malaisie", "de": "Malaysia"},
    "MV": {"en": "Maldives", "it": "Maldive", "es": "Maldivas", "fr": "Maldives", "de": "Malediven"},
    "ML": {"en": "Mali", "it": "Mali", "es": "Mali", "fr": "Mali", "de": "Mali"},
    "MT": {"en": "Malta", "it": "Malta", "es": "Malta", "fr": "Malte", "de": "Malta"},
    "MH": {"en": "Marshall Islands", "it": "Isole Marshall", "es": "Islas Marshall", "fr": "Îles Marshall", "de": "Marshallinseln"},
    "MQ": {"en": "Martinique", "it": "Martinica", "es": "Martinica", "fr": "Martinique", "de": "Martinique"},
    "MR": {"en": "Mauritania", "it": "Mauritania", "es": "Mauritania", "fr": "Mauritanie", "de": "Mauretanien"},
    "MU": {"en": "Mauritius", "it": "Mauritius", "es": "Mauricio", "fr": "Maurice", "de": "Mauritius"},
    "YT": {"en": "Mayotte", "it": "Mayotte", "es": "Mayotte", "fr": "Mayotte", "de": "Mayotte"},
    "MX": {"en": "Mexico", "it": "Messico", "es": "México", "fr": "Mexique", "de": "Mexiko"},
    "FM": {"en": "Micronesia", "it": "Micronesia", "es": "Micronesia", "fr": "Micronésie", "de": "Mikronesien"},
    "MD": {"en": "Moldova", "it": "Moldavia", "es": "Moldavia", "fr": "Moldavie", "de": "Moldawien"},
    "MC": {"en": "Monaco", "it": "Monaco", "es": "Mónaco", "fr": "Monaco", "de": "Monaco"},
    "MN": {"en": "Mongolia", "it": "Mongolia", "es": "Mongolia", "fr": "Mongolie", "de": "Mongolei"},
    "ME": {"en": "Montenegro", "it": "Montenegro", "es": "Montenegro", "fr": "Monténégro", "de": "Montenegro"},
    "MS": {"en": "Montserrat", "it": "Montserrat", "es": "Montserrat", "fr": "Montserrat", "de": "Montserrat"},
    "MA": {"en": "Morocco", "it": "Marocco", "es": "Marruecos", "fr": "Maroc", "de": "Marokko"},
    "MZ": {"en": "Mozambique", "it": "Mozambico", "es": "Mozambique", "fr": "Mozambique", "de": "Mosambik"},
    "MM": {"en": "Myanmar", "it": "Myanmar", "es": "Myanmar", "fr": "Birmanie", "de": "Myanmar"},
    "NA": {"en": "Namibia", "it": "Namibia", "es": "Namibia", "fr": "Namibie", "de": "Namibia"},
    "NR": {"en": "Nauru", "it": "Nauru", "es": "Nauru", "fr": "Nauru", "de": "Nauru"},
    "NP": {"en": "Nepal", "it": "Nepal", "es": "Nepal", "fr": "Népal", "de": "Nepal"},
    "NL": {"en": "Netherlands", "it": "Paesi Bassi", "es": "Países Bajos", "fr": "Pays-Bas", "de": "Niederlande"},
    "NC": {"en": "New Caledonia", "it": "Nuova Caledonia", "es": "Nueva Caledonia", "fr": "Nouvelle-Calédonie", "de": "Neukaledonien"},
    "NZ": {"en": "New Zealand", "it": "Nuova Zelanda", "es": "Nueva Zelanda", "fr": "Nouvelle-Zélande", "de": "Neuseeland"},
    "NI": {"en": "Nicaragua", "it": "Nicaragua", "es": "Nicaragua", "fr": "Nicaragua", "de": "Nicaragua"},
    "NE": {"en": "Niger", "it": "Niger", "es": "Níger", "fr": "Niger", "de": "Niger"},
    "NG": {"en": "Nigeria", "it": "Nigeria", "es": "Nigeria", "fr": "Nigeria", "de": "Nigeria"},
    "NU": {"en": "Niue", "it": "Niue", "es": "Niue", "fr": "Niue", "de": "Niue"},
    "NF": {"en": "Norfolk Island", "it": "Isola Norfolk", "es": "Isla Norfolk", "fr": "Île Norfolk", "de": "Norfolkinsel"},
    "MP": {"en": "Northern Mariana Islands", "it": "Isole Marianne Settentrionali", "es": "Islas Marianas del Norte", "fr": "Îles Mariannes du Nord", "de": "Nördliche Marianen"},
    "NO": {"en": "Norway", "it": "Norvegia", "es": "Noruega", "fr": "Norvège", "de": "Norwegen"},
    "OM": {"en": "Oman", "it": "Oman", "es": "Omán", "fr": "Oman", "de": "Oman"},
    "PK": {"en": "Pakistan", "it": "Pakistan", "es": "Pakistán", "fr": "Pakistan", "de": "Pakistan"},
    "PW": {"en": "Palau", "it": "Palau", "es": "Palaos", "fr": "Palaos", "de": "Palau"},
    "PS": {"en": "Palestinian Territories", "it": "Territori Palestinesi", "es": "Territorios Palestinos", "fr": "Territoires Palestiniens", "de": "Palästinensische Gebiete"},
    "PA": {"en": "Panama", "it": "Panama", "es": "Panamá", "fr": "Panama", "de": "Panama"},
    "PG": {"en": "Papua New Guinea", "it": "Papua Nuova Guinea", "es": "Papúa Nueva Guinea", "fr": "Papouasie-Nouvelle-Guinée", "de": "Papua-Neuguinea"},
    "PY": {"en": "Paraguay", "it": "Paraguay", "es": "Paraguay", "fr": "Paraguay", "de": "Paraguay"},
    "PE": {"en": "Peru", "it": "Peru", "es": "Perú", "fr": "Pérou", "de": "Peru"},
    "PH": {"en": "Philippines", "it": "Filippine", "es": "Filipinas", "fr": "Philippines", "de": "Philippinen"},
    "PN": {"en": "Pitcairn Islands", "it": "Isole Pitcairn", "es": "Islas Pitcairn", "fr": "Îles Pitcairn", "de": "Pitcairninseln"},
    "PL": {"en": "Poland", "it": "Polonia", "es": "Polonia", "fr": "Pologne", "de": "Polen"},
    "PT": {"en": "Portugal", "it": "Portogallo", "es": "Portugal", "fr": "Portugal", "de": "Portugal"},
    "PR": {"en": "Puerto Rico", "it": "Porto Rico", "es": "Puerto Rico", "fr": "Porto Rico", "de": "Puerto Rico"},
    "QA": {"en": "Qatar", "it": "Qatar", "es": "Catar", "fr": "Qatar", "de": "Katar"},
    "RE": {"en": "Reunion", "it": "Reunion", "es": "Reunión", "fr": "Réunion", "de": "Réunion"},
    "RO": {"en": "Romania", "it": "Romania", "es": "Rumania", "fr": "Roumanie", "de": "Rumänien"},
    "RU": {"en": "Russia", "it": "Russia", "es": "Rusia", "fr": "Russie", "de": "Russland"},
    "RW": {"en": "Rwanda", "it": "Ruanda", "es": "Ruanda", "fr": "Rwanda", "de": "Ruanda"},
    "BL": {"en": "Saint Barthelemy", "it": "Saint-Barthelemy", "es": "San Bartolomé", "fr": "Saint-Barthélemy", "de": "Saint-Barthélemy"},
    "SH": {"en": "Saint Helena, Ascension and Tristan da Cunha", "it": "Sant Elena, Ascensione e Tristan da Cunha", "es": "Santa Helena, Ascensión y Tristán da Cunha", "fr": "Sainte-Hélène, Ascension et Tristan da Cunha", "de": "St. Helena, Ascension und Tristan da Cunha"},
    "KN": {"en": "Saint Kitts and Nevis", "it": "Saint Kitts e Nevis", "es": "San Cristóbal y Nieves", "fr": "Saint-Christophe-et-Niévès", "de": "St. Kitts und Nevis"},
    "LC": {"en": "Saint Lucia", "it": "Saint Lucia", "es": "Santa Lucía", "fr": "Sainte-Lucie", "de": "St. Lucia"},
    "MF": {"en": "Saint Martin (French part)", "it": "Saint-Martin (parte francese)", "es": "San Martín (parte francesa)", "fr": "Saint-Martin (partie française)", "de": "Saint-Martin (französischer Teil)"},
    "PM": {"en": "Saint Pierre and Miquelon", "it": "Saint-Pierre e Miquelon", "es": "San Pedro y Miquelón", "fr": "Saint-Pierre-et-Miquelon", "de": "Saint-Pierre und Miquelon"},
    "VC": {"en": "Saint Vincent and the Grenadines", "it": "Saint Vincent e Grenadine", "es": "San Vicente y las Granadinas", "fr": "Saint-Vincent-et-les-Grenadines", "de": "St. Vincent und die Grenadinen"},
    "WS": {"en": "Samoa", "it": "Samoa", "es": "Samoa", "fr": "Samoa", "de": "Samoa"},
    "SM": {"en": "San Marino", "it": "San Marino", "es": "San Marino", "fr": "Saint-Marin", "de": "San Marino"},
    "ST": {"en": "Sao Tome and Principe", "it": "Sao Tome e Principe", "es": "Santo Tomé y Príncipe", "fr": "Sao Tomé-et-Principe", "de": "São Tomé und Príncipe"},
    "SA": {"en": "Saudi Arabia", "it": "Arabia Saudita", "es": "Arabia Saudí", "fr": "Arabie Saoudite", "de": "Saudi-Arabien"},
    "SN": {"en": "Senegal", "it": "Senegal", "es": "Senegal", "fr": "Sénégal", "de": "Senegal"},
    "RS": {"en": "Serbia", "it": "Serbia", "es": "Serbia", "fr": "Serbie", "de": "Serbien"},
    "SC": {"en": "Seychelles", "it": "Seychelles", "es": "Seychelles", "fr": "Seychelles", "de": "Seychellen"},
    "SL": {"en": "Sierra Leone", "it": "Sierra Leone", "es": "Sierra Leona", "fr": "Sierra Leone", "de": "Sierra Leone"},
    "SG": {"en": "Singapore", "it": "Singapore", "es": "Singapur", "fr": "Singapour", "de": "Singapur"},
    "SX": {"en": "Sint Maarten (Dutch part)", "it": "Sint Maarten (parte olandese)", "es": "Sint Maarten (parte neerlandesa)", "fr": "Sint Maarten (partie néerlandaise)", "de": "Sint Maarten (niederländischer Teil)"},
    "SK": {"en": "Slovakia", "it": "Slovacchia", "es": "Eslovaquia", "fr": "Slovaquie", "de": "Slowakei"},
    "SI": {"en": "Slovenia", "it": "Slovenia", "es": "Eslovenia", "fr": "Slovénie", "de": "Slowenien"},
    "SB": {"en": "Solomon Islands", "it": "Isole Salomone", "es": "Islas Salomón", "fr": "Îles Salomon", "de": "Salomonen"},
    "SO": {"en": "Somalia", "it": "Somalia", "es": "Somalia", "fr": "Somalie", "de": "Somalia"},
    "ZA": {"en": "South Africa", "it": "Sudafrica", "es": "Sudáfrica", "fr": "Afrique du Sud", "de": "Südafrika"},
    "GS": {"en": "South Georgia and the South Sandwich Islands", "it": "Georgia del Sud e Isole Sandwich Australi", "es": "Georgia del Sur e Islas Sandwich del Sur", "fr": "Géorgie du Sud et Îles Sandwich du Sud", "de": "Südgeorgien und die Südlichen Sandwichinseln"},
    "SS": {"en": "South Sudan", "it": "Sudan del Sud", "es": "Sudán del Sur", "fr": "Soudan du Sud", "de": "Südsudan"},
    "ES": {"en": "Spain", "it": "Spagna", "es": "España", "fr": "Espagne", "de": "Spanien"},
    "LK": {"en": "Sri Lanka", "it": "Sri Lanka", "es": "Sri Lanka", "fr": "Sri Lanka", "de": "Sri Lanka"},
    "SD": {"en": "Sudan", "it": "Sudan", "es": "Sudán", "fr": "Soudan", "de": "Sudan"},
    "SR": {"en": "Suriname", "it": "Suriname", "es": "Surinam", "fr": "Surinam", "de": "Suriname"},
    "SJ": {"en": "Svalbard and Jan Mayen", "it": "Svalbard e Jan Mayen", "es": "Svalbard y Jan Mayen", "fr": "Svalbard et Jan Mayen", "de": "Spitzbergen und Jan Mayen"},
    "SZ": {"en": "Eswatini", "it": "Eswatini", "es": "Eswatini", "fr": "Eswatini", "de": "Eswatini"},
    "SE": {"en": "Sweden", "it": "Svezia", "es": "Suecia", "fr": "Suède", "de": "Schweden"},
    "CH": {"en": "Switzerland", "it": "Svizzera", "es": "Suiza", "fr": "Suisse", "de": "Schweiz"},
    "SY": {"en": "Syria", "it": "Siria", "es": "Siria", "fr": "Syrie", "de": "Syrien"},
    "TW": {"en": "Taiwan", "it": "Taiwan", "es": "Taiwán", "fr": "Taiwan", "de": "Taiwan"},
    "TJ": {"en": "Tajikistan", "it": "Tagikistan", "es": "Tayikistán", "fr": "Tadjikistan", "de": "Tadschikistan"},
    "TZ": {"en": "Tanzania", "it": "Tanzania", "es": "Tanzania", "fr": "Tanzanie", "de": "Tansania"},
    "TH": {"en": "Thailand", "it": "Tailandia", "es": "Tailandia", "fr": "Thaïlande", "de": "Thailand"},
    "TL": {"en": "Timor-Leste", "it": "Timor Est", "es": "Timor Oriental", "fr": "Timor oriental", "de": "Osttimor"},
    "TG": {"en": "Togo", "it": "Togo", "es": "Togo", "fr": "Togo", "de": "Togo"},
    "TK": {"en": "Tokelau", "it": "Tokelau", "es": "Tokelau", "fr": "Tokelau", "de": "Tokelau"},
    "TO": {"en": "Tonga", "it": "Tonga", "es": "Tonga", "fr": "Tonga", "de": "Tonga"},
    "TT": {"en": "Trinidad and Tobago", "it": "Trinidad e Tobago", "es": "Trinidad y Tobago", "fr": "Trinité-et-Tobago", "de": "Trinidad und Tobago"},
    "TN": {"en": "Tunisia", "it": "Tunisia", "es": "Túnez", "fr": "Tunisie", "de": "Tunesien"},
    "TR": {"en": "Turkey", "it": "Turchia", "es": "Turquía", "fr": "Turquie", "de": "Türkei"},
    "TM": {"en": "Turkmenistan", "it": "Turkmenistan", "es": "Turkmenistán", "fr": "Turkménistan", "de": "Turkmenistan"},
    "TC": {"en": "Turks and Caicos Islands", "it": "Isole Turks e Caicos", "es": "Islas Turcas y Caicos", "fr": "Îles Turques-et-Caïques", "de": "Turks- und Caicosinseln"},
    "TV": {"en": "Tuvalu", "it": "Tuvalu", "es": "Tuvalu", "fr": "Tuvalu", "de": "Tuvalu"},
    "UG": {"en": "Uganda", "it": "Uganda", "es": "Uganda", "fr": "Ouganda", "de": "Uganda"},
    "UA": {"en": "Ukraine", "it": "Ucraina", "es": "Ucrania", "fr": "Ukraine", "de": "Ukraine"},
    "AE": {"en": "United Arab Emirates", "it": "Emirati Arabi Uniti", "es": "Emiratos Árabes Unidos", "fr": "Émirats Arabes Unis", "de": "Vereinigte Arabische Emirate"},
    "GB": {"en": "United Kingdom", "it": "Regno Unito", "es": "Reino Unido", "fr": "Royaume-Uni", "de": "Vereinigtes Königreich"},
    "US": {"en": "United States", "it": "Stati Uniti", "es": "Estados Unidos", "fr": "États-Unis", "de": "Vereinigte Staaten"},
    "UM": {"en": "United States Minor Outlying Islands", "it": "Isole minori esterne degli Stati Uniti", "es": "Islas Periféricas Menores de EE.UU.", "fr": "Îles mineures éloignées des États-Unis", "de": "Außengebiete der Vereinigten Staaten"},
    "UY": {"en": "Uruguay", "it": "Uruguay", "es": "Uruguay", "fr": "Uruguay", "de": "Uruguay"},
    "UZ": {"en": "Uzbekistan", "it": "Uzbekistan", "es": "Uzbekistán", "fr": "Ouzbékistan", "de": "Usbekistan"},
    "VU": {"en": "Vanuatu", "it": "Vanuatu", "es": "Vanuatu", "fr": "Vanuatu", "de": "Vanuatu"},
    "VE": {"en": "Venezuela", "it": "Venezuela", "es": "Venezuela", "fr": "Venezuela", "de": "Venezuela"},
    "VN": {"en": "Vietnam", "it": "Vietnam", "es": "Vietnam", "fr": "Viêt Nam", "de": "Vietnam"},
    "VG": {"en": "British Virgin Islands", "it": "Isole Vergini britanniche", "es": "Islas Vírgenes Británicas", "fr": "Îles Vierges Britanniques", "de": "Britische Jungferninseln"},
    "VI": {"en": "U.S. Virgin Islands", "it": "Isole Vergini americane", "es": "Islas Vírgenes de los EE.UU.", "fr": "Îles Vierges des États-Unis", "de": "Amerikanische Jungferninseln"},
    "WF": {"en": "Wallis and Futuna", "it": "Wallis e Futuna", "es": "Wallis y Futuna", "fr": "Wallis-et-Futuna", "de": "Wallis und Futuna"},
    "EH": {"en": "Western Sahara", "it": "Sahara Occidentale", "es": "Sáhara Occidental", "fr": "Sahara Occidental", "de": "Westsahara"},
    "YE": {"en": "Yemen", "it": "Yemen", "es": "Yemen", "fr": "Yémen", "de": "Jemen"},
    "ZM": {"en": "Zambia", "it": "Zambia", "es": "Zambia", "fr": "Zambie", "de": "Sambia"},
    "ZW": {"en": "Zimbabwe", "it": "Zimbabwe", "es": "Zimbabue", "fr": "Zimbabwe", "de": "Simbabwe"},
}


def get_country_name(code: str, lang: str = "en") -> str:

    code_upper = code.upper() if code else ""
    lang_lower = lang.lower() if lang else "en"
    
    data = country_codes.get(code_upper)
    if data:
        name = data.get(lang_lower) or data.get("en")
        return f"{code_upper} {name}"
    return f"{code_upper} Not available"
